apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-user-deployment
  namespace: taskflow
  labels:
    app: taskflow-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-user
  template:
    metadata:
      labels:
        app: taskflow-user
    spec:
      containers:
      - name: user-svc
        image: 383189130746.dkr.ecr.us-east-1.amazonaws.com/taskflow-user:1
        
        env:
        - name: DB_NAME
          value: "users_db"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        envFrom:
        - configMapRef:
            name: services-cm        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20  
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10

        ports:
        - containerPort: 8001


