apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-notification-deployment
  namespace: taskflow
  labels:
    app: taskflow-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-notification
  template:
    metadata:
      labels:
        app: taskflow-notification
    spec:
      containers:
      - name: notifications-svc
        image: 383189130746.dkr.ecr.us-east-1.amazonaws.com/taskflow-notification:27473599777
       
        envFrom:
        - configMapRef:
            name: services-cm 
        env:
        - name: DB_NAME
          value: notifications_db
        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: DB_PASSWORD
              
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 20
    
        ports:
        - containerPort: 8004

