apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-task-deployment
  namespace: taskflow
  labels:
    app: taskflow-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-task
  template:
    metadata:
      labels:
        app: taskflow-task
    
    spec:
      containers:
      - name: task-svc
        image: 383189130746.dkr.ecr.us-east-1.amazonaws.com/taskflow-task:27474349756
        
        envFrom:
        - configMapRef:
            name: services-cm  
        env:
        - name: DB_NAME
          value: tasks_db
        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: DB_PASSWORD
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 20 
        
        ports:
        - containerPort: 8003

