apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-task-deployment
  namespace: taskflow
  labels:
    app: taskflow-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskflow-task
  template:
    metadata:
      labels:
        app: taskflow-task
    
    spec:
      initContainers:
      - name: waitforpostgress
        image: busybox
        envFrom:
        - configMapRef:
            name: services-cm
        command: ['sh', '-c', 'until nc -z $DB_HOST 5432; do echo waiting; sleep 2; done']
      
      containers:
      - name: task-svc
        image: 
        
        env:
        - name: DB_NAME
          value: users_db
        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: DB_PASSWORD
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 20 
        
        ports:
        - containerPort: 8003

