apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend-deployment
  namespace: taskflow
  labels:
    app: taskflow-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
      - name: frontend
        image: 383189130746.dkr.ecr.us-east-1.amazonaws.com/taskflow-frontend:27473374095
        ports:
        - containerPort: 80

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
